# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 12:57
from __future__ import unicode_literals

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20170411_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='thumbnail',
            field=models.FileField(default=0, upload_to=articles.models.get_upload_file_name),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
